<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="WIN-NO5VUV5PR36" name="pe.com.test.seleniumwd.CategoriaWebDriverTest" tests="5" failures="1" timestamp="22 May 2018 14:55:57 GMT" time="92.151" errors="0">
  <testcase name="actualizarCategoria" time="19.391" classname="pe.com.test.seleniumwd.CategoriaWebDriverTest"/>
  <testcase name="eliminarCategoria" time="19.392" classname="pe.com.test.seleniumwd.CategoriaWebDriverTest">
    <failure type="java.lang.AssertionError" message="expected [Se eliminó de manera correcta la Categoría] but found []">
      <![CDATA[java.lang.AssertionError: expected [Se eliminó de manera correcta la Categoría] but found []
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at pe.com.test.seleniumwd.CategoriaWebDriverTest.eliminarCategoria(CategoriaWebDriverTest.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- eliminarCategoria -->
  <testcase name="insertarCategoria" time="15.272" classname="pe.com.test.seleniumwd.CategoriaWebDriverTest"/>
  <testcase name="actualizarCategoria" time="19.516" classname="pe.com.test.seleniumwd.CategoriaWebDriverTest"/>
  <testcase name="insertarCategoria" time="18.580" classname="pe.com.test.seleniumwd.CategoriaWebDriverTest"/>
</testsuite> <!-- pe.com.test.seleniumwd.CategoriaWebDriverTest -->
